### ISSUE TITLE
Initial clone + build fails on module resolution for `zotero-types`

### ISSUE THREAD

**Issue by whacked** [windingwind/zotero-addon-template#1]
Hi, I'm following the template instructions step-by-step. Pardon my basic questions; I am not familiar with `esbuild`.

I have:
1. cloned the respository
2. modified package.json
3. run `npm install`
4. run `npm run build`

at which point, the build fails with these errors:
```
[Build] BUILD_DIR=builds, VERSION=0.0.0, BUILD_TIME=2022-08-31 10:26:14
✘ [ERROR] Could not resolve "zotero-types"

    src/index.ts:1:23:
      1 │ import { Zotero } from "zotero-types";
        ╵                        ~~~~~~~~~~~~~~

  You can mark the path "zotero-types" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "zotero-types"

    src/views.ts:1:28:
      1 │ import { XUL, Zotero } from "zotero-types";
        ╵                             ~~~~~~~~~~~~~~

  You can mark the path "zotero-types" as external to exclude it from the bundle, which will remove
  this error.

✘ [ERROR] Could not resolve "zotero-types"

    src/events.ts:1:23:
      1 │ import { Zotero } from "zotero-types";
        ╵                        ~~~~~~~~~~~~~~

  You can mark the path "zotero-types" as external to exclude it from the bundle, which will remove
  this error.
```

## Additional information:
- `zotero-types` exists in `node_modules`, among 348 total folders in `node_modules` following `npm install`. `zotero-types` contains README.md, package.json, and index.d.ts
- following the error message, I modify `build.js` this way:
```javascript
await esbuild
  .build({
    entryPoints: ["src/index.ts"],
    external: ["zotero-types"],       // <--- add this line
    bundle: true,
    // Entry should be the same as add ...
    outfile: path.join(buildDir, "addo ...
    // minify: true,                  
  })
  .catch(() => process.exit(1));      
```

and it appears to build ok. Is this the correct fix?

## system information

```
[nix-shell:/tmp/zotero-addon-template]$ echo $NODE_PATH
/tmp/zotero-addon-template/node_modules

[nix-shell:/tmp/zotero-addon-template]$ node --version
v18.7.0

[nix-shell:/tmp/zotero-addon-template]$ npm --version
8.15.0
```

thank you for your work

**Comment by windingwind** [comment]
Sorry, this is a bug caused by the upper-stream dependency `zotero-types` and I have just fixed it.

Making it external might not be the right way. Please pull the latest changes of this repo and update the npm package `zotero-types`. Make sure it is >= v0.0.3.

**Comment by whacked** [comment]
Confirmed that updating to zotero-types 0.0.3 and `npm build` without the `external` hack succeeds.

thanks!

**Comment by windingwind** [comment]
Just to remind, the bootstrap mode is now available. The overlay mode will no longer be supported in Zotero 7(though may be years later). If you just started, please consider switching to bootstrap mode.
